<a href="https://colab.research.google.com/github/Tanishqchahal/Powerplant-ouput-predictor/blob/main/PowerplantOutput.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Importing the Libraries

In [1]:
import numpy as np
import pandas as pd

##Part-1 Data Preprocessing


###Importing the dataset

In [2]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [3]:
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [4]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [5]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

###Splitting the dataset into training set and test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

##Part-2 Building ANN

In [7]:
import tensorflow as tf

In [8]:
from keras.models import Sequential
from keras.layers import Dense

###Initialising the ANN

In [9]:
ann = Sequential()

###Adding the input layer and the first hidden layer

In [10]:
ann.add(Dense(6,activation = 'relu'))

###Adding the second hidden layer

In [11]:
ann.add(Dense(6,activation = 'relu'))

###Adding the output layer

In [12]:
ann.add(Dense(1))

###Compiling the ANN

In [13]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

##Part-3 Training the ANN

###Training the ANN on the training set

In [14]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 30)

Epoch 1/30
240/240 [==============================] - 3s 3ms/step - loss: 7322.6982
Epoch 2/30
240/240 [==============================] - 1s 3ms/step - loss: 87.7759
Epoch 3/30
240/240 [==============================] - 1s 4ms/step - loss: 84.9134
Epoch 4/30
240/240 [==============================] - 1s 3ms/step - loss: 81.3494
Epoch 5/30
240/240 [==============================] - 1s 2ms/step - loss: 77.2130
Epoch 6/30
240/240 [==============================] - 1s 3ms/step - loss: 72.6206
Epoch 7/30
240/240 [==============================] - 1s 4ms/step - loss: 67.6460
Epoch 8/30
240/240 [==============================] - 0s 2ms/step - loss: 62.5997
Epoch 9/30
240/240 [==============================] - 0s 2ms/step - loss: 57.5502
Epoch 10/30
240/240 [==============================] - 0s 2ms/step - loss: 52.4684
Epoch 11/30
240/240 [==============================] - 0s 2ms/step - loss: 47.5292
Epoch 12/30
240/240 [==============================] - 0s 2ms/step - loss: 43.2330
Epoch 13/30

###Predicting the output on the test set

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test), 1)),1))

60/60 [==============================] - 0s 1ms/step
[[435.66 431.23]
 [463.06 460.01]
 [467.73 461.14]
 ...
 [474.01 473.26]
 [440.79 438.  ]
 [460.63 463.28]]
